# frozen_string_literal: true

require_relative "common"

module Input
  module Validators
    # HashValidation
    #
    # Responsibilities:
    # - Ensure an attribute value is a Hash when present.
    # - Support nested hash validation via either:
    #   - an inline `Input` class (provided through a block), or
    #   - a reference to an existing class via `from:`.
    # - Register default values for hash attributes on the declaring class.
    #
    # Usage examples:
    #   # simple hash
    #   optional(:metadata).hash
    #
    #   # nested hash via block
    #   required(:address).hash do
    #     required(:city).string
    #   end
    #
    #   # nested hash via existing class
    #   required(:billing).hash(from: BillingInput)
    module HashValidation
      # Attach hash validation to `klass` for the attribute `name`.
      # `nested_klass` is an inline class generated by a block.
      # `from` can be a Class or a constant name that will be resolved
      # at runtime. Registers the nested class on the declaring class
      # so validation can be performed later.
      def self.attach(klass, name, nested_klass: nil, from: nil, **options)
        if nested_klass
          Common.add_nested_class(klass, name, nested_klass)
        elsif from
          resolved = Common.resolve_const(from)
          Common.add_nested_class(klass, name, resolved) if resolved
        end

        klass.validate do
          target = Common.resolve_const(nested_klass || from)
          HashValidation.validate_hash_value(self, name, target, **options)
        end
      end

      # Validate the hash value on an instance. Ensures the attribute is
      # a Hash when present. Respects `allow_blank` to skip validation if
      # the attribute is not set. When a nested target class exists, it
      # instantiates that class and merges its validation errors onto the
      # parent with a dotted key (e.g. `address.city`).
      # rubocop:disable Metrics/AbcSize, Metrics/MethodLength, Metrics/CyclomaticComplexity, Metrics/PerceivedComplexity
      def self.validate_hash_value(instance, name, target, **options)
        format = options[:format] || {}
        err_message = format[:message] || "#{name.to_s.titleize} must be a hash"

        value = instance[name]
        return unless instance.attributes.key?(name)
        return if value.blank? && format[:allow_blank]
        return instance.errors.add(:base, err_message) unless value.is_a?(Hash)

        nested = target.new(value)
        return if nested.valid?

        nested.errors.each do |err|
          message = format_error_message(err)
          instance.errors.add("#{name}.#{err.attribute}", message)
        end
      end
      # rubocop:enable Metrics/AbcSize, Metrics/MethodLength, Metrics/CyclomaticComplexity, Metrics/PerceivedComplexity

      # Format an `ActiveModel::Error` into a human-friendly message.
      def self.format_error_message(err)
        Common.format_error_message(err)
      end
    end
  end
end
