# frozen_string_literal: true

require_relative "common"

module Input
  module Validators
    # HashValidation
    #
    # Responsibilities:
    # - Validate that a declared attribute is a Hash when present.
    # - Support nested hash validation by allowing either an inline
    #   `Input` class (provided via a block) or a reference via `from:`.
    # - Register defaults for hash attributes on the owning class.
    #
    # Usage examples:
    #   # simple hash
    #   optional(:metadata).hash
    #
    #   # nested hash via block
    #   required(:address).hash do
    #     required(:city).string
    #   end
    #
    #   # nested hash via existing class
    #   required(:billing).hash(from: BillingInput)
    module HashValidation
      # Attach hash validation to `klass` for the attribute `name`.
      # `nested_klass` is an inline class generated by a block. `from`
      # can be a Class or a constant name that will be resolved at runtime.
      def self.attach(klass, name, nested_klass: nil, from: nil)
        if nested_klass
          Common.add_nested_class(klass, name, nested_klass)
        elsif from
          resolved = Common.resolve_const(from)
          Common.add_nested_class(klass, name, resolved) if resolved
        end

        klass.validate do
          target = Common.resolve_const(nested_klass || from)
          HashValidation.validate_hash_value(self, name, target)
        end
      end

      # Validate the hash value on an instance. Ensures the attribute is a
      # Hash and, when a nested target class exists, instantiates that
      # class and merges its validation errors onto the parent with a
      # dotted key (e.g. `address.city`).
      def self.validate_hash_value(instance, name, target)
        value = instance[name]
        return if value.nil?
        return instance.errors.add(name, "must be a hash") unless value.is_a?(Hash)
        return instance.errors.add(name, "internal: nested class not found") unless target

        nested = target.new(value)
        return if nested.valid?

        nested.errors.each do |err|
          message = format_error_message(err)
          instance.errors.add("#{name}.#{err.attribute}", message)
        end
      end

      # Format an `ActiveModel::Error` into a human-friendly message.
      def self.format_error_message(err)
        Common.format_error_message(err)
      end
    end
  end
end
